behaviors:
  ShootingAgent:
    trainer_type: ppo
    hyperparameters:
    # common to PPO and SAC
      batch_size: 1024 #512 #2000 #10 #128
      buffer_size: 10240 #4096 #100 #2048
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      # PPo-specific
      beta: 1.0e-2 #5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3 #8 

#      beta_schedule: constant
#      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128 #256 #512
      num_layers: 2 #2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1 #1
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 5000